# aws endpoint version
services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
    restart: always

  backend:
    image: siatlth/siat-git-action-backend
    container_name: backend-spring-container
    ports:
      - "8087:8087"
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - redis

  nginx:
    build:
      context: ./nginx
    container_name: nginx-reverse-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - /etc/letsencrypt/live/api.siathub.com/fullchain.pem:/etc/nginx/ssl/api.siathub.crt
      - /etc/letsencrypt/live/api.siathub.com/privkey.pem:/etc/nginx/ssl/api.siathub.key
    depends_on:
      - backend

