server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  port: 8087
spring:
  data:
    redis:
      host: redis
      port: 6379
  sql:
    init:
      mode: always
      encoding: UTF-8
  config:
    import: optional:application-secret.yml
  messages:
    encoding: UTF-8
  application:
    name: backend
  datasource:
    driverClassName: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:h2:mem:testdb?useUnicode=true&characterEncoding=utf8;MODE=PostgreSQL;DATABASE_TO_UPPER=false;
    username: sa
    password:
mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  config-location: classpath:/mybatis-config.xml
logging:
  level:
    com.takoyakki.backend: DEBUG
    org.mybatis: DEBUG
    org.mybatis.spring.SqlSessionFactoryBean: DEBUG
    java.sql.Connection: DEBUG
    java.sql.Statement: DEBUG
    java.sql.PreparedStatement: DEBUG
    com.p6spy: DEBUG
p6spy:
  config:
    logMessageFormat: com.p6spy.engine.spy.appender.MultiLineFormat
    appender: com.p6spy.engine.spy.appender.Slf4JLogger
    logLevel: debug